services:
  postgres:
    image: postgres:16
    container_name: alepostgres
    environment:
      POSTGRES_DB: aledb
      POSTGRES_USER: ale
      POSTGRES_PASSWORD: ale
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data:mode=0700,uid=999,gid=999
